### ISSUE TITLE
Ai on 7840hs works or not ?

### ISSUE THREAD

**Issue by alphagoa** [realKarthikNair/16-xf0xxx-linux-troubleshooting#1]
7840hs has ai enabled at hardware level ,but can you check whether hp had enabled it or not .

**Comment by realKarthikNair** [comment]
I will check and revert whenever I boot to Windows. Give me 2 days tops.

**Comment by realKarthikNair** [comment]
Yes it does. 

![image](https://github.com/realKarthikNair/16-xf0xxx-linux-troubleshooting/assets/78267371/3dfde7eb-994b-4903-a579-13879866fd98)
